### PR TITLE
Update actor.mjs to resolve speed as int

### PR DESCRIPTION
**Pull request by vertigoogle**
This makes the speed attribute easier for use in modules like the drag ruler

### CODE REVIEW

**Comment by vertigoogle** [comment]
Please check for side effects as I did not read the whole system code :)

**Comment by kypvalanx** [comment]
i've been working pretty head down on updates for the last month and just saw this.  i'll take a look soon.

**Comment by kypvalanx** [comment]
this is resolved as a string including the movement type because of the multiple movement types.  idk how the plugin works, but could an int version of the speed be returned from another getter?  this getter is used to populate the sheet itself.

**Comment by vertigoogle** [comment]
Hi, indeed a new getter would fit also.
Shall I implement one or would you like to do this?

**Pull request closed without merging**
