### PR TITLE
Bug Fix for #155

### PR DESCRIPTION
**Pull request by Orkah**
Fix wiki URLs for packs/swse-items.db & packs/swse-affiliations.db.
URL for https://swse.fandom.com/ was undefined, therefore pointing to http://localhost:30000/

https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/issues/154#issue-1181200997

### CODE REVIEW

**Comment by Orkah** [comment]
Added packs/swse-templates.db for the same issue.

**Comment by Orkah** [comment]
Fixes for #159 & #155 added as well.

**Comment by Orkah** [comment]
Fix for #160 added

**Comment by kypvalanx** [comment]
direct commits to the db files are not permitted.  these files are generated and any future generation will overwrite these files.  the change to ignore constitution looks good, i'll merge once you remove the other changes.

**Comment by Orkah** [comment]
DB files are up to date with 0.5.5.
#154, #159 & #160 remain unresolved in that commit (Removed)
Fix for #155 only.

**Comment by Orkah** [comment]
All done. 
Thanks for the feedback. If you need anything, please ask. I am willing to help.
And thanks again for your work ;) Have a great day.

**Comment by kypvalanx** [comment]
I looked more closely into it, and your fix would have broken vehicles since that's what the || true was added to help.  instead i've had it check for an undefined con score and return true when it is undefined.  thank you for your help on this.

**Pull request closed without merging**
